All:
	gcc ./main.c -o main_intelSntx_x86_64bit.s -S -masm=intel -m64
		# -m64 https://www.geeksforgeeks.org/compile-32-bit-program-64-bit-gcc-c-c/
	
	gcc ./main_intelSntx_x86_64bit.s -o main_intelSntx_x86_64bit

	./main_intelSntx_x86_64bit





	