All:
	gcc ./main.c -o main_intelSntx_x86_64bit.s -S -masm=intel -m64
		# -m64 https://www.geeksforgeeks.org/compile-32-bit-program-64-bit-gcc-c-c/
		# -m32 sudo apt-get install gcc-multilib g++-multilib https://askubuntu.com/questions/453681/gcc-wont-link-with-m32
	
	gcc ./main_intelSntx_x86_64bit.s -o main_intelSntx_x86_64bit

	./main_intelSntx_x86_64bit





	